FROM python:3.11-slim

WORKDIR /app
COPY producer/requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY producer/ /app/
COPY ["исходные данные/", "/app/data/"]

CMD ["python", "producer.py"]
